from fpdf import FPDF
from datetime import datetime

# =====================================================
# PDF REPORT GENERATOR
# =====================================================

def generate_pdf_report(

    username,

    filename,

    attack_count,

    benign_count,

    attack_percentage,

    health_score

):

    pdf = FPDF()

    pdf.add_page()

    # =================================================
    # TITLE
    # =================================================

    pdf.set_font(
        "Arial",
        "B",
        20
    )

    pdf.cell(
        200,
        10,
        "GNN IDS Threat Report",
        ln=True,
        align="C"
    )

    pdf.ln(10)

    # =================================================
    # USER INFO
    # =================================================

    pdf.set_font(
        "Arial",
        "",
        12
    )

    pdf.cell(
        200,
        10,
        f"Generated By: {username}",
        ln=True
    )

    pdf.cell(
        200,
        10,
        f"Dataset: {filename}",
        ln=True
    )

    pdf.cell(
        200,
        10,
        f"Generated On: {datetime.now()}",
        ln=True
    )

    pdf.ln(10)

    # =================================================
    # RESULTS
    # =================================================

    pdf.set_font(
        "Arial",
        "B",
        14
    )

    pdf.cell(
        200,
        10,
        "Threat Analysis Results",
        ln=True
    )

    pdf.set_font(
        "Arial",
        "",
        12
    )

    pdf.cell(
        200,
        10,
        f"Attack Traffic: {attack_count}",
        ln=True
    )

    pdf.cell(
        200,
        10,
        f"Benign Traffic: {benign_count}",
        ln=True
    )

    pdf.cell(
        200,
        10,
        f"Threat Percentage: {attack_percentage:.2f}%",
        ln=True
    )

    pdf.cell(
        200,
        10,
        f"Network Health Score: {health_score:.2f}%",
        ln=True
    )

    pdf.ln(10)

    # =================================================
    # AI RECOMMENDATIONS
    # =================================================

    pdf.set_font(
        "Arial",
        "B",
        14
    )

    pdf.cell(
        200,
        10,
        "AI Security Recommendations",
        ln=True
    )

    pdf.set_font(
        "Arial",
        "",
        12
    )

    recommendations = [

        "- Enable firewall monitoring",

        "- Block suspicious IP addresses",

        "- Monitor unusual packet spikes",

        "- Use multi-layer authentication",

        "- Continuously monitor network traffic"
    ]

    for rec in recommendations:

        pdf.cell(
            200,
            10,
            rec,
            ln=True
        )

    # =================================================
    # SAVE PDF
    # =================================================

    report_name = "gnn_ids_report.pdf"

    pdf.output(report_name)

    return report_name